baseURL = "https://alvr.dev"
title = "dev, alvr"
theme = "fixit"
copyright = '© 2013 — 2022 Álvaro Salcedo García | [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0 "License")'
defaultContentLanguage = "es"
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true
googleAnalytics = "UA-37621780-1"
paginate = 4
relativeURLs = true
removePathAccents = true
rssLimit = 100
summaryLength = 70
timeZone = "Europe/Madrid"

[author]
name = "alvr"
email = "alvaro@alvr.dev"
link = ""
avatar = "/images/alvr.webp"

[markup]
defaultMarkdownHandler = "goldmark"

  [markup.asciidocExt]
  attributes = { }
  backend = "html5"
  extensions = [ ]
  failureLevel = "fatal"
  noHeaderOrFooter = true
  preserveTOC = false
  safeMode = "unsafe"
  sectionNumbers = false
  trace = false
  verbose = false
  workingFolderCurrent = false

  [markup.blackFriday]
  angledQuotes = false
  footnoteAnchorPrefix = ""
  footnoteReturnLinkContents = ""
  fractions = true
  hrefTargetBlank = false
  latexDashes = true
  nofollowLinks = false
  noreferrerLinks = false
  plainIDAnchors = true
  skipHTML = false
  smartDashes = true
  smartypants = true
  smartypantsQuotesNBSP = false
  taskLists = true

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

  [markup.goldmark.parser.attribute]
  block = false
  title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

  [markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = false

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.css]
keepCSS2 = true
precision = 0

[minify.tdewolff.html]
keepComments = false
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = true
keepWhitespace = false

[minify.tdewolff.js]
keepVarNames = false
precision = 0

[minify.tdewolff.json]
keepNumbers = false
precision = 0

[minify.tdewolff.svg]
precision = 0

[minify.tdewolff.xml]
keepWhitespace = false

[outputs]
home = [ "HTML", "JSON", "RSS" ]
page = [ "HTML" ]
section = [ "HTML" ]
taxonomy = [ "HTML" ]
term = [ "HTML" ]

[permalinks]
posts = "/post/:slug"
tags = "/tag/:slug"

[related]
includeNewer = false
threshold = 80
toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 100

  [[related.indices]]
  name = "date"
  weight = 10

[security]
enableInlineShortcodes = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
