main:
  - identifier: about
    name: About me
    url: about-me/
    weight: 1

  - identifier: archive
    name: Archive
    url: archive/
    weight: 2
  
  - identifier: projects
    name: Projects
    url: projects/
    weight: 3

  - identifier: cv
    name: CV
    url: cv/
    weight: 4
  
  - identifier: contact
    name: Contact
    url: contact/
    weight: 5

  # Submenus
  - identifier: android
    parent: projects
    name: Android
    url: projects/android/
    weight: 1

  - identifier: docker
    parent: projects
    name: Docker
    url: projects/docker/
    weight: 2

  - identifier: web
    parent: projects
    name: Web
    url: projects/web/
    weight: 3