main:
  - identifier: about
    name: Sobre mí
    url: sobre-mi/
    weight: 1

  - identifier: archive
    name: Archivo
    url: archivo/
    weight: 2
  
  - identifier: projects
    name: Proyectos
    url: proyectos/
    weight: 3

  - identifier: cv
    name: CV
    url: cv/
    weight: 4
  
  - identifier: contact
    name: Contactar
    url: contactar/
    weight: 5