main:
  - identifier: about
    name: Sobre mí
    url: sobre-mi/
    weight: 1

  - identifier: archive
    name: Archivo
    url: archivo/
    weight: 2
  
  - identifier: projects
    name: Proyectos
    url: proyectos/
    weight: 3

  - identifier: cv
    name: CV
    url: cv/
    weight: 4
  
  - identifier: contact
    name: Contactar
    url: contactar/
    weight: 5

  # Submenús
  - identifier: android
    parent: projects
    name: Android
    url: proyectos/android/
    weight: 1

  - identifier: docker
    parent: projects
    name: Docker
    url: proyectos/docker/
    weight: 2

  - identifier: web
    parent: projects
    name: Web
    url: proyectos/web/
    weight: 3