title: dev, alvr
description: Random things by a random human.
keywords: [blog, portfolio, personal, programming, android]
author: Álvaro Salcedo García
images: [/images/alvr.webp]
DateFormat: January 2, 2006
defaultTheme: dark
disableThemeToggle: true
ShowReadingTime: true
ShowShareButtons: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowFullTextinRSS: true
ShareButtons: [twitter, facebook, linkedin, whatsapp, telegram]
disableSpecial1stPost: false
disableScrollToTop: false
displayFullLangName: true
comments: true
hidemeta: false
hideSummary: false
hideFooter: true
showtoc: true
tocopen: false

assets:
  disableHLJS: false
  disableFingerprinting: false

socialIcons:
  - name: github
    url: https://github.com/alvr
  - name: gitlab
    url: https://gitlab.com/alvr
  - name: keybase
    url: https://keybase.io/alvr
  - name: kofi
    url: https://ko-fi.com/alvrSG
  - name: linkedin
    url: https://linkedin.com/in/alvr
  - name: twitter
    url: https://twitter.com/alvrSG
  - name: email
    url: mailto:alvaro@alvr.dev
  - name: rss
    url: index.xml

cover:
  responsiveImages: true
  hidden: false
  hiddenInList: true
  hiddenInSingle: true

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: [title, permalink, summary, content]