version = "0.2.18"
description = "Random things by a random human."
keywords = [ "blog", "portfolio", "personal", "programming", "android" ]
defaultTheme = "dark"
gitRepo = "https://github.com/alvr/me"
fingerprint = ""
dateFormat = "January 2, 2006"
images = [ "/images/alvr.webp" ]
enablePWA = true
externalIcon = true
disableThemeInject = false

[app]
title = "dev, alvr"
noFavicon = false
svgFavicon = ""
iconColor = "#5bbad5"
tileColor = "#da532c"
  [app.themeColor]
  light = "#f8f8f8"
  dark = "#3b3b3b"

[search]
enable = true
type = "fuse"
contentLength = 4000
placeholder = ""
maxResultLength = 10
snippetLength = 30
highlightTag = "em"
absoluteURL = false
  [search.algolia]
  index = ""
  appID = ""
  searchKey = ""

  [search.fuse]
  isCaseSensitive = false
  minMatchCharLength = 2
  findAllMatches = false
  location = 0
  threshold = 0.3
  distance = 100
  ignoreLocation = false
  useExtendedSearch = false
  ignoreFieldNorm = false

[header]
desktopMode = "normal"
mobileMode = "auto"
  [header.title]
  logo = ""
  name = "dev, alvr"
  pre = "&#128104;&#8205;&#128187;"
  post = ""
  typeit = false

  [header.subtitle]
  name = ""
  typeit = false

[breadcrumb]
  enable = true
  sticky = false
  showHome = false

[footer]
enable = true
custom = ""
hugo = false
copyright = true
author = true
since = 2013
wordCount = true
gov = ""
icp = ""
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a> <script defer src="https://stats.alvr.dev/script.js" data-website-id="b0b27133-4e06-4b30-8171-7db3b94a9720"></script>'
  [footer.siteTime]
  enable = false
  animate = false
  icon = "fa-solid fa-heartbeat"
  pre = ""
  value = ""

  [footer.order]
  powered = 0
  copyright = 0
  statistics = 0
  visitor = 0
  beian = 0

[section]
paginate = 7
dateFormat = "2 January"
rss = 10
  [section.recentlyUpdated]
  enable = false
  rss = false
  days = 30
  maxCount = 10

[list]
paginate = 7
dateFormat = "2 January"
rss = 10

[tagcloud]
enable = false
min = 14
max = 32
peakCount = 10
orderby = "name"

[home]
rss = 10
  [home.profile]
  enable = true
  gravatarEmail = "alvaro@alvr.dev"
  avatarURL = "/images/alvr.webp"
  avatarMenu = "about"
  title = "dev, alvr"
  subtitle = "Random things by a random human."
  typeit = true
  social = true
  disclaimer = ""

  [home.posts]
  enable = false
  paginate = 6

[social]
GitHub = "alvr"
Linkedin = "alvr"
Twitter = "alvrSG"
Stackoverflow = "1882643"
Paypal = "alvaro"
Mastodon = "@alvr"
RSS = true

[page]
authorAvatar = true
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = true
lightgallery = true
ruby = true
fraction = true
fontawesome = true
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
linkToMarkdown = true
rssFullText = false
pageStyle = "narrow"
autoBookmark = false
wordCount = true
readingTime = true
endFlag = ""
instantPage = true
  [page.repost]
  enable = false
  url = ""

  [page.toc]
  enable = true
  keepStatic = false
  auto = true
  position = "right"

  [page.expirationReminder]
  enable = false
  reminder = 90
  warning = 180
  closeComment = false

  [page.math]
  enable = true
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  copyTex = true
  mhchem = true

  [page.code]
  copy = true
  edit = true
  maxShownLines = 10
  
  [page.edit]
  enable = false
  url = ""

  [page.mapbox]
  accessToken = ""
  lightStyle = "mapbox://styles/mapbox/light-v9"
  darkStyle = "mapbox://styles/mapbox/dark-v9"
  navigation = true
  geolocate = true
  scale = true
  fullscreen = true

  [page.reward]
  enable = false
  animation = false
  position = "after"
    [page.reward.ways]
    wechatpay = ""
    alipay = ""
    paypal = ""
    bitcoin = ""

  [page.share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  Whatsapp = true
  Weibo = false

  [page.comment]
  enable = true
    [page.comment.giscus]
    enable = true
    repo = "alvr/me"
    repoId = "MDEwOlJlcG9zaXRvcnk5NjU1NTE2Mg=="
    category = "Posts"
    categoryId = "DIC_kwDOBcFQms4CT_pc"
    mapping = "pathname"
    term = ""
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    lightTheme = "light"
    darkTheme = "dark"
    lazyLoad = true

  [page.library]
    [page.library.css]
    # someCSS = "some.css"
    # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
    # someJavascript = "some.js"
    # someJavascript = "https://cdn.example.com/some.js"

  [page.seo]
  images = ["images/alvr.webp"]
    [page.seo.publisher]
    name = "Álvaro Salcedo García"
    logoUrl = "images/alvr.webp"

[typeit]
speed = 100
cursorSpeed = 1000
cursorChar = "|"
duration = -1

[mermaid]
themes = ["dark"]

[watermark]
enable = false
content = ""
opacity = 0.1
appendTo = ".wrapper>main"
width = 150
height = 20
rowSpacing = 60
colSpacing = 30
rotate = 15
fontSize = 0.85
fontFamily = "inherit"

[verification]
google = ""
bing = ""
yandex = ""
pinterest = ""
baidu = ""
so = ""
sogou = ""

[seo]
image = ""
thumbnailUrl = ""

[analytics]
enable = true
  [analytics.google]
  id = "UA-37621780-1"
  anonymizeIP = true

  [analytics.fathom]
  id = ""
  server = ""

[cookieconsent]
enable = false
  [cookieconsent.content]
  message = ""
  dismiss = ""
  link = ""

[cdn]
data = ""

[compatibility]
polyfill = false
objectFit = false

[githubCorner]
enable = false
permalink = "https://github.com/hugo-fixit/FixIt"
title = "View source on GitHub"
position = "right"

[gravatar]
host = "www.gravatar.com"
style = "retro"

[backToTop]
enable = true
scrollpercent = false

[readingProgress]
enable = true
start = "left"
position = "top"
reversed = false
light = ""
dark = "#d6d6d6"
height = "2px"

[pace]
enable = true
color = "silver"
theme = "minimal"

[customFilePath]
# aside = "custom/aside.html"
# profile = "custom/profile.html"
# footer = "custom/footer.html"

[dev]
enable = false
c4u = false
githubToken = ""

[dev.mDevtools]
enable = false
type = "vConsole"
