baseurl = "https://alvr.me"
DefaultContentLanguage = "es"
title = "me, alvr"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "alvr"
googleAnalytics = "UA-37621780-1"

[taxonomies]
  tag = "tags"

[Params]
  subtitle = "Random things by a random human."
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "02/01/2006"
  commit = "https://github.com/alvr/alvr.github.io/commit/"
  rss = true
  comments = true
  readingTime = true
  useHLJS = false
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  gcse = "009995410285976540412:vistk49srvs"
  since = 2013


[Author]
  name = "Álvaro S."
  email = "alvaro@alvr.me"
  github = "alvr"
  gitlab = "alvr"
  twitter = "alvrSG"
  steam = "Alvaro_SG"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Proyectos"
    url = "proyectos/"
    weight = 2

[[menu.main]]
    name = "Contactar"
    url = "contactar/"
    weight = 3

[[menu.main]]
    name = "Etiquetas"
    url = "tags/"
    weight = 4