[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	  debug = false

[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"

# [[plugins]]
#   package = "netlify-plugin-checklinks"
#   [plugins.inputs]
#     entryPoints = [".css", "*.html", "*.js"]
#     recursive = true
#     pretty = true
#     checkExternal = false

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = ["production"]
  [plugins.inputs.minifierOptions]
    collapseInlineTagWhitespace = false
    collapseWhitespace = true
    minifyCSS = true
    minifyJS = true
    minifyURLs = true
    removeComments = true
    sortAttributes = true
    sortClassName = true

[[redirects]]
  from = "https://alvr.netlify.app/*"
  to = "https://alvr.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://master--alvr.netlify.app/*"
  to = "https://alvr.dev/:splat"
  status = 301
  force = true
