[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
    baseUrl = "https://alvr.dev"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[plugins]]
  package = "netlify-plugin-service-worker"

[[redirects]]
  from = "https://alvr.netlify.app/*"
  to = "https://alvr.dev/:splat"
  status = 301
  force = true