[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-purge-cloudflare-on-deploy"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
    baseUrl = "https://alvr.dev"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[plugins]]
  package = "netlify-plugin-service-worker"

[[plugins]]
  package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ["master"]
  mainBranch = "master"
  pathPrefix = "/"
  customDomain = "alvr.dev"
  renderJavaScript = true
